Repository 3S-CREW/Chaining, pull requests merged in 2025-09, with the labels that each got.

#43 [#39] 모집글 상세 보기의 신청 버튼과 지원서 제출 화면 연결
  .idea/other.xml
  app/build.gradle.kts
  app/src/main/java/com/example/chaining/data/repository/ApplicationRepository.kt
  app/src/main/java/com/example/chaining/domain/model/RecruitPost.kt
  app/src/main/java/com/example/chaining/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/chaining/ui/navigation/Screen.kt
  app/src/main/java/com/example/chaining/ui/screen/CommunityScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/JoinPostScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/ViewPostScreen.kt
  app/src/main/java/com/example/chaining/viewmodel/ApplicationViewModel.kt
Labels: enhancement

#51 [Design]모집글 UI 1차수정
  app/src/main/java/com/example/chaining/ui/component/SaveButton.kt
  app/src/main/java/com/example/chaining/ui/screen/CommunityScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MainHomeScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyApplyScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/ViewPostScreen.kt
  app/src/main/res/drawable/post.png
  app/src/main/res/drawable/reload.png
Labels: design

#56 [Design] 퀴즈 UI 1차수정
  app/src/main/java/com/example/chaining/ui/screen/ENQuizScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/KRQuizScreen.kt
  app/src/main/java/com/example/chaining/viewmodel/QuizViewModel.kt
Labels: design

#61 [#60] Feat : 화면 간 네비게이션 연결
  app/src/main/java/com/example/chaining/ui/component/TestButton.kt
  app/src/main/java/com/example/chaining/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/chaining/ui/screen/CommunityScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/HomeScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MainHomeScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyApplyScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyPageScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/ViewPostScreen.kt
Labels: design

#65 [Feat] 피드 UI
  app/src/main/java/com/example/chaining/ui/component/FeedItem.kt
  app/src/main/java/com/example/chaining/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/chaining/ui/navigation/Screen.kt
  app/src/main/java/com/example/chaining/ui/screen/FeedScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/HomeScreen.kt
Labels: enhancement

#68 [#66] Feat : 내 모집글 모아보기 UI 생성 및 DB 연동
  app/src/main/java/com/example/chaining/data/local/Converters.kt
  app/src/main/java/com/example/chaining/data/local/entity/UserEntity.kt
  app/src/main/java/com/example/chaining/data/repository/RecruitPostRepository.kt
  app/src/main/java/com/example/chaining/data/repository/UserRepository.kt
  app/src/main/java/com/example/chaining/domain/model/User.kt
  app/src/main/java/com/example/chaining/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/chaining/ui/navigation/Screen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyPageScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyPostsScreen.kt
Labels: enhancement, design

#69 [#67] Feat : 내 지원서 모아보기 UI 생성 및 DB 연동
  app/src/main/java/com/example/chaining/data/local/Converters.kt
  app/src/main/java/com/example/chaining/data/local/entity/UserEntity.kt
  app/src/main/java/com/example/chaining/data/repository/ApplicationRepository.kt
  app/src/main/java/com/example/chaining/data/repository/UserRepository.kt
  app/src/main/java/com/example/chaining/domain/model/User.kt
  app/src/main/java/com/example/chaining/ui/component/CardItem.kt
  app/src/main/java/com/example/chaining/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/chaining/ui/navigation/Screen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyApplicationsScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyPageScreen.kt
Labels: bug, enhancement, design

#77 [Feat] 앱 아이콘
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: enhancement

#78 [#70] Feat : 수정 삭제 멀티패스 업데이트
  app/src/main/java/com/example/chaining/data/repository/RecruitPostRepository.kt
  app/src/main/java/com/example/chaining/domain/model/RecruitPost.kt
  app/src/main/java/com/example/chaining/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/chaining/ui/navigation/Screen.kt
  app/src/main/java/com/example/chaining/ui/screen/CreatePostScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/ViewPostScreen.kt
  app/src/main/java/com/example/chaining/viewmodel/RecruitPostViewModel.kt
Labels: enhancement, design

#80 [Feat] 피드 api
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/chaining/data/model/FeedApiResponse.kt
  app/src/main/java/com/example/chaining/data/repository/FeedRepository.kt
  app/src/main/java/com/example/chaining/di/FeedModule.kt
  app/src/main/java/com/example/chaining/network/FeedApiService.kt
  app/src/main/java/com/example/chaining/ui/component/FeedItem.kt
  app/src/main/java/com/example/chaining/ui/screen/FeedScreen.kt
  app/src/main/java/com/example/chaining/viewmodel/FeedViewModel.kt
  app/src/main/res/xml/network_security_config.xml
Labels: enhancement

#81 [#73] Feat : 마이페이지 사진 업로드 기능 생성
  app/build.gradle.kts
  app/src/main/java/com/example/chaining/data/repository/UserRepository.kt
  app/src/main/java/com/example/chaining/ui/screen/MyPageScreen.kt
  app/src/main/java/com/example/chaining/viewmodel/UserViewModel.kt
Labels: enhancement

#98 [Design] 총 UI 3차수정
  app/build.gradle.kts
  app/src/main/java/com/example/chaining/ui/component/CardItem.kt
  app/src/main/java/com/example/chaining/ui/component/FilterOptionSheet.kt
  app/src/main/java/com/example/chaining/ui/component/FollowNotificationItem.kt
  app/src/main/java/com/example/chaining/ui/component/SaveButton.kt
  app/src/main/java/com/example/chaining/ui/component/TestButton.kt
  app/src/main/java/com/example/chaining/ui/login/LoginScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/ApplicationsScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/CommunityScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/CreatePostScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/FeedScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/JoinPostScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MainHomeScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyPageScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyPostsScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/NotificationScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/ViewPostScreen.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  hs_err_pid1800.log
  replay_pid1800.log
Labels: design

#102 [Design] 총 UI 4차수정
  app/src/main/java/com/example/chaining/ui/component/FeedItem.kt
  app/src/main/java/com/example/chaining/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/chaining/ui/screen/ApplicationsScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/CreatePostScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/JoinPostScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MyPageScreen.kt
  app/src/main/java/com/example/chaining/viewmodel/ApplicationViewModel.kt
  app/src/main/java/com/example/chaining/viewmodel/RecruitPostViewModel.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: design

#113 [Design] 총 UI 7차수정
  app/src/main/java/com/example/chaining/ui/navigation/NavGraph.kt
  app/src/main/java/com/example/chaining/ui/screen/ApplyScreen.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
  hs_err_pid14604.log
  replay_pid14604.log
Labels: design

#119 [Design] 총 UI 9차수정
  .kotlin/errors/errors-1758100641387.log
  app/src/main/assets/korean_quizzes.json
  app/src/main/java/com/example/chaining/domain/model/QuizItem.kt
  app/src/main/java/com/example/chaining/ui/component/FeedItem.kt
  app/src/main/java/com/example/chaining/ui/screen/CommunityScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/ENQuizScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/FeedScreen.kt
  app/src/main/java/com/example/chaining/ui/screen/MainHomeScreen.kt
  app/src/main/java/com/example/chaining/viewmodel/QuizViewModel.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: design
